# docker-compose.yml
# $ docker compose up -d --build

version: "3.9"

name: grindurus-app

networks:
  grindurus:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: app
    restart: unless-stopped
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 3001"
    networks:
      - grindurus
    labels:
      - traefik.enable=true
      - traefik.docker.network=grindurus
      
      # --- HTTP → HTTPS redirect ---
      - traefik.http.routers.app.rule=Host(`app.${DOMAIN:-localhost}`)
      - traefik.http.routers.app.tls.certresolver=le
      - traefik.http.routers.app.entrypoints=websecure

      # --- general backend ---
      - traefik.http.services.app.loadbalancer.server.port=3001